name: 检查文件是否生成

on:
  workflow_dispatch:

jobs:
  run-get-update:
    runs-on: ubuntu-latest

    steps:
    # 检出代码
    - name: Checkout repository
      uses: actions/checkout@v3

      # 2. 动态生成 var.json 文件
    - name: Generate var.json
      run: |
          echo '{
            "token": "'"${{ secrets.TOKEN }}"'",
            "username": "'"${{ secrets.USERNAME }}"'",
            "password": "'"${{ secrets.PASSWORD }}"'",
            "from_email": "'"${{ secrets.FROM_EMAIL }}"'",
            "to_email": "'"${{ secrets.TO_EMAIL }}"'",
            "email_token": "'"${{ secrets.EMAIL_TOKEN }}"'"
          }' > copymanga/var.json
          cat copymanga/var.json
